// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Fibo-1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Fibo-1', async function() {
    await driver.get("https://calculations-mery.herokuapp.com/")
    await driver.manage().window().setRect({ width: 945, height: 1020 })
    await driver.findElement(By.css("a:nth-child(1) > button")).click()
    await driver.findElement(By.css("button:nth-child(2)")).click()
  })
})
